global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'trip-service'
    static_configs:
      - targets: ['trip-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'risk-service'
    static_configs:
      - targets: ['risk-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricing-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    metrics_path: '/admin/metrics'
    scrape_interval: 30s

